# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				ender_dragon = true
				evoker = true
				llama_spit = true
				glow_squid = true
				squid = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				elder_guardian = true
				small_fireball = true
				boat = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true

			[light_sources.settings.entities.gobber2]
				nemesis = true

			[light_sources.settings.entities.revamped_phantoms]
				shockwave = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				octopus = true
				goose = true
				songbird = true
				badgerdirt = true
				eel_freshwater = true
				squid_giant = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				shark = true
				flying_fish = true
				piranha = true
				bobbit_worm = true
				barracuda = true
				nautilus = true
				moose = true
				tarantula = true
				badger = true
				eel_saltwater = true
				squirrel = true
				brownbear = true
				walrus = true
				horseshoecrab = true
				turkey = true
				coyote = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				gauntlet = true
				void_blossom = true

			[light_sources.settings.entities.golemsgalore]
				quartz_golem = true
				obsidian_golem = true
				amethyst_golem = true
				laser_golem = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				revenant = true
				skeleton_creeper = true
				ghoul = true
				reaper = true
				nightmare = true

			[light_sources.settings.entities.byg]
				boat = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				naga = true

			[light_sources.settings.entities.adventurez]
				deer = true
				skeleton_vanguard = true
				orc = true
				necromancer = true
				ender_whale = true
				blaze_guardian = true
				small_stone_golem = true
				piglin_beast = true
				shaman = true
				blaze_guardian_shield = true
				brown_fungus = true
				nightmare = true
				mammoth = true
				stone_golem = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				amethyst_shard = true
				summoner = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				end_fish = true

			[light_sources.settings.entities.edenring]
				diskwing = true
				lightning_ray = true

